version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: treeone_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: treeone_app
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_DB: ${REDIS_DB}
    ports:
      - "8080:8080"

  redis:
    image: redis:7
    container_name: treeone_redis
    restart: always
    ports:
      - "6379:6379"
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://postgres:1234@postgres:5432/treeone?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres
    restart: "on-failure"

volumes:
  pgdata:
